{
	"AddRevitServicesDocumentAndTransactionManager": {
		"prefix": "addserv",
		"body": [
			"clr.AddReference(\"RevitServices\")",
			"from RevitServices.Persistence import DocumentManager",
			"from RevitServices.Transactions import TransactionManager",
			"",
			"",
			"doc = DocumentManager.Instance.CurrentDBDocument",
			"uiapp = DocumentManager.Instance.CurrentUIApplication",
			"app = uiapp.Application"
		],
		"description": "Добавление RevitServices"
	},
	"AddRevitAPI": {
		"prefix": "addapi",
		"body": [
			"import clr",
			"clr.AddReference(\"RevitAPI\")",
			"from Autodesk.Revit.DB import "
		],
		"description": "Добавление RevitAPI"
	},
	"FirstRowInIronPythonProject": {
		"prefix": "!",
		"body": "# -*- coding: utf-8 -*-"
	},

	"uiapp" : {
		"prefix": "uiapp",
		"body": [
			"uiapp = DocumentManager.Instance.CurrentUIApplication",
			"app = uiapp.Application"
		]
	},

	"Transaction": {
		"prefix": "trans",
		"body": [
			"TransactionManager.Instance.EnsureInTransaction(doc)",
			"",
			"${1}",
			"",
			"TransactionManager.Instance.TransactionTaskDone()"
		]
	},

	"addapiui": {
		"prefix": "addapiui",
		"body": [
			"clr.AddReference('RevitAPIUI')",
			"from Autodesk.Revit.UI.Selection import ObjectType, Selection"
		]
	},
	"UnwrapElement": {
		"prefix": "unwrap",
		"body": [
			"UnwrapElement(${1})  # noqa"
		]
	},
	"RevitNodes": {
		"prefix": "rvtnodes",
		"body": [
			"clr.AddReference(\"RevitNodes\")",
			"import Revit",
			"clr.ImportExtensions(Revit.Elements)",
			"clr.ImportExtensions(Revit.GeometryConversion)"
		]
	}

}